-   id: add-missing-init
    name: add-missing-init
    description: Add a __init__.py file to each directory containing python source code.
    entry: add-missing-init
    language: python
    language_version: python3
    pass_filenames: true
    types_or: [python, directory]
    require_serial: true
    minimum_pre_commit_version: 1.6.0
