-   id: add-missing-init
    name: add-missing-init
    description: Add a __init__.py file to each directoryadd_missing_init.py that contains .py files.
    entry: add-missing-init
    language: python
    language_version: python3
    pass_filenames: true
    args: src
    types: [file, python]
    verbose: true
    require_serial: true
    minimum_pre_commit_version: 1.6.0
