-   id: add-missing-init
    name: Add missing __init__.py files
    description: Add a __init__.py file to each directory containing python source code.
    entry: add-missing-init
    language: python
    language_version: python3
    types: [python]
    require_serial: true
    minimum_pre_commit_version: 1.6.0
